---
- name: Create RegUser on OOD
  user:
    name: "{{ RegUser_app_user }}"
    comment: "{{ RegUser_app_user_full_name }}"
    shell: /bin/bash
    createhome: no
    state: present
    system: yes

- name: Remove existing user register app install
  file:
    path: "{{ account_app_path }}"
    state: absent

- name: Clone user register app form from gitlab
  git:
    repo: "{{ account_app_repo }}"
    dest: "{{ account_app_path }}"
    refspec: "{{ account_app_refspec }}"
    version: "{{ account_app_tag }}"

- name: Change ownership of directory
  file:
    path: "{{ account_app_path }}"
    owner: root
    group: root
    state: directory
    recurse: yes

- name: Create __pycache__ directories with proper ownership
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ RegUser_app_user }}"
    group: "{{ RegUser_app_user }}"
  loop:
    - "{{ account_app_path }}/__pycache__"
    - "{{ account_app_path }}/app/__pycache__"

- name: Copy Self-Reg app variables file
  template:
    src: app_vars.j2
    dest: "{{ account_app_path }}/app_vars.py"

- name: Install requirements in virtualenv
  pip:
    requirements: requirements.txt
    virtualenv: venv
    chdir: "{{ account_app_path }}"

- name: Install gunicorn in virtualenv
  pip:
    name: gunicorn
    virtualenv: venv
    virtualenv_command: /usr/bin/python3 -m venv
    chdir: "{{ account_app_path }}"

- name: Create log directory
  file:
    path: "/var/log/{{ account_app }}"
    owner: "{{ RegUser_app_user }}"
    group: "{{ RegUser_app_user }}"
    state: directory

- name: Set up log rotate for module usage
  template:
    src: logrotate.j2
    dest: "/etc/logrotate.d/{{ account_app }}"

- name: Copy Celery service template
  template:
    src: celery.service.j2
    dest: "/etc/systemd/system/celery-{{ account_app }}.service"

- name: Enable celery.service
  systemd:
    name: celery-{{ account_app }}.service
    enabled: yes

- name: Put gunicorn config file in place
  template:
    src: ini.j2
    dest: "{{ account_app_path }}/{{ account_app }}.ini"

- name: Create gunicorn system service
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{ account_app }}.service"

- name: Start and enable flask app gunicorn service
  service:
    name: "{{ account_app }}"
    enabled: yes
